# Generated by Django 4.0 on 2022-08-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videoId',
            field=models.CharField(max_length=255),
        ),
    ]
